DELETE FROM Languages 
DBCC CHECKIDENT ('Languages', RESEED, 0)



INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Abkhazian',N'аҧсуа бызшәа аҧсшәа',N'ab',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Afar',N'Afaraf',N'aa',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Afrikaans',N'Afrikaans',N'af',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Akan',N'Akan',N'ak',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Albanian',N'Shqip',N'sq',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Amharic',N'አማርኛ',N'am',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Arabic',N'العربية',N'ar',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Aragonese',N'aragonés',N'an',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Armenian',N'Հայերեն',N'hy',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Assamese',N'অসমীয়া',N'as',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Avaric',N'авар мацӀ магӀарул мацӀ',N'av',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Avestan',N'avesta',N'ae',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Aymara',N'aymar aru',N'ay',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Azerbaijani',N'azərbaycan dili',N'az',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Bambara',N'bamanankan',N'bm',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Bashkir',N'башҡорт теле',N'ba',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Basque',N'euskara euskera',N'eu',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Belarusian',N'беларуская мова',N'be',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Bengali',N'বাংলা',N'bn',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Bihari languages',N'भोजपुरी',N'bh',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Bislama',N'Bislama',N'bi',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Bosnian',N'bosanski jezik',N'bs',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Breton',N'brezhoneg',N'br',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Bulgarian',N'български език',N'bg',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Burmese',N'ဗမာစာ',N'my',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Catalan Valencian',N'català valencià',N'ca',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Chamorro',N'Chamoru',N'ch',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Chechen',N'нохчийн мотт',N'ce',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Chichewa Chewa Nyanja',N'chiCheŵa chinyanja',N'ny',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Chinese',N'中文(Zhōngwén) 汉语 漢語',N'zh',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Chuvash',N'чӑваш чӗлхи',N'cv',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Cornish',N'Kernewek',N'kw',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Corsican',N'corsu lingua corsa',N'co',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Cree',N'ᓀᐦᐃᔭᐍᐏᐣ',N'cr',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Croatian',N'hrvatski jezik',N'hr',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Czech',N'čeština český jazyk',N'cs',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Danish',N'dansk',N'da',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Divehi Dhivehi Maldivian',N'ދިވެހި',N'dv',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Dutch Flemish',N'Nederlands Vlaams',N'nl',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Dzongkha',N'རྫོང་ཁ',N'dz',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'English',N'English',N'en',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Esperanto',N'Esperanto',N'eo',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Estonian',N'eesti eesti keel',N'et',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Ewe',N'Eʋegbe',N'ee',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Faroese',N'føroyskt',N'fo',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Fijian',N'vosa Vakaviti',N'fj',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Finnish',N'suomi suomen kieli',N'fi',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'French',N'français langue française',N'fr',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Fulah',N'Fulfulde Pulaar Pular',N'ff',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Galician',N'Galego',N'gl',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Georgian',N'ქართული',N'ka',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'German',N'Deutsch',N'de',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Greek (modern)',N'ελληνικά',N'el',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Guaraní',N'Avañe ẽ',N'gn',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Gujarati',N'ગુજરાતી',N'gu',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Haitian Haitian Creole',N'Kreyòl ayisyen',N'ht',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Hausa',N'(Hausa) هَوُسَ',N'ha',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Hebrew (modern)',N'עברית',N'he',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Herero',N'Otjiherero',N'hz',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Hindi',N'हिन्दी हिंदी',N'hi',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Hiri Motu',N'Hiri Motu',N'ho',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Hungarian',N'magyar',N'hu',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Interlingua',N'Interlingua',N'ia',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Indonesian',N'Bahasa Indonesia',N'id',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Interlingue',N'Originally called Occidental; then Interlingue after WWII',N'ie',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Irish',N'Gaeilge',N'ga',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Igbo',N'Asụsụ Igbo',N'ig',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Inupiaq',N'Iñupiaq Iñupiatun',N'ik',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Ido',N'Ido',N'io',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Icelandic',N'Íslenska',N'is',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Italian',N'Italiano',N'it',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Inuktitut',N'ᐃᓄᒃᑎᑐᑦ',N'iu',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Japanese',N'日本語 (にほんご)',N'ja',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Javanese',N'ꦧꦱꦗꦮ Basa Jawa',N'jv',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Kalaallisut Greenlandic',N'kalaallisut kalaallit oqaasii',N'kl',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Kannada',N'ಕನ್ನಡ',N'kn',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Kanuri',N'Kanuri',N'kr',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Kashmiri',N'कश्मीरी كشميري‎',N'ks',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Kazakh',N'қазақ тілі',N'kk',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Central Khmer',N'ខ្មែរ ខេមរភាសា ភាសាខ្មែរ',N'km',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Kikuyu Gikuyu',N'Gĩkũyũ',N'ki',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Kinyarwanda',N'Ikinyarwanda',N'rw',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Kirghiz Kyrgyz',N'Кыргызча Кыргыз тили',N'ky',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Komi',N'коми кыв',N'kv',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Kongo',N'Kikongo',N'kg',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Korean',N'한국어',N'ko',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Kurdish',N'Kurdî کوردی‎',N'ku',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Kuanyama Kwanyama',N'Kuanyama',N'kj',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Latin',N'latine lingua latina',N'la',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Luxembourgish Letzeburgesch',N'Lëtzebuergesch',N'lb',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Ganda',N'Luganda',N'lg',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Limburgan Limburger Limburgish',N'Limburgs',N'li',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Lingala',N'Lingála',N'ln',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Lao',N'ພາສາລາວ',N'lo',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Lithuanian',N'lietuvių kalba',N'lt',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Luba-Katanga',N'Kiluba',N'lu',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Latvian',N'latviešu valoda',N'lv',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Manx',N'Gaelg Gailck',N'gv',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Macedonian',N'македонски јазик',N'mk',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Malagasy',N'fiteny malagasy',N'mg',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Malay',N'Bahasa Melayu بهاس ملايو‎',N'ms',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Malayalam',N'മലയാളം',N'ml',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Maltese',N'Malti',N'mt',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Maori',N'te reo Māori',N'mi',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Marathi',N'मराठी',N'mr',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Marshallese',N'Kajin M̧ajeļ',N'mh',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Mongolian',N'Монгол хэл',N'mn',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Nauru',N'Dorerin Naoero',N'na',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Navajo Navaho',N'Diné bizaad',N'nv',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'North Ndebele',N'isiNdebele',N'nd',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Nepali',N'नेपाली',N'ne',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Ndonga',N'Owambo',N'ng',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Norwegian Bokmål',N'Norsk Bokmål',N'nb',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Norwegian Nynorsk',N'Norsk Nynorsk',N'nn',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Norwegian',N'Norsk',N'no',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Sichuan Yi Nuosu',N'ꆈꌠ꒿ Nuosuhxop',N'ii',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'South Ndebele',N'isiNdebele',N'nr',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Occitan',N'occitan lenga d òc',N'oc',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Ojibwa',N'ᐊᓂᔑᓈᐯᒧᐎᓐ',N'oj',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Church Slavic Church Slavonic Old Church Slavonic Old Slavonic Old Bulgarian',N'ѩзыкъ словѣньскъ',N'cu',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Oromo',N'Afaan Oromoo',N'om',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Oriya',N'ଓଡ଼ିଆ',N'or',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Ossetian Ossetic',N'ирон æвзаг',N'os',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Panjabi Punjabi',N'ਪੰਜਾਬੀ',N'pa',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Pali',N'पाऴि',N'pi',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Persian',N'فارسی',N'fa',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Polish',N'język polski polszczyzna',N'pl',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Pashto Pushto',N'پښتو',N'ps',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Portuguese',N'Português',N'pt',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Quechua',N'Runa Simi Kichwa',N'qu',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Romansh',N'Rumantsch Grischun',N'rm',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Rundi',N'Ikirundi',N'rn',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Romanian Moldavian Moldovan',N'Română',N'ro',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Russian',N'русский',N'ru',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Sanskrit',N'संस्कृतम्',N'sa',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Sardinian',N'sardu',N'sc',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Sindhi',N'सिन्धी سنڌي، سندھی‎',N'sd',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Northern Sami',N'Davvisámegiella',N'se',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Samoan',N'gagana fa a Samoa',N'sm',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Sango',N'yângâ tî sängö',N'sg',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Serbian',N'српски језик',N'sr',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Gaelic Scottish Gaelic',N'Gàidhlig',N'gd',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Shona',N'chiShona',N'sn',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Sinhala Sinhalese',N'සිංහල',N'si',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Slovak',N'Slovenčina Slovenský Jazyk',N'sk',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Slovene',N'Slovenski Jezik Slovenščina',N'sl',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Somali',N'Soomaaliga af Soomaali',N'so',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Southern Sotho',N'Sesotho',N'st',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Spanish Castilian',N'Español',N'es',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Sundanese',N'Basa Sunda',N'su',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Swahili',N'Kiswahili',N'sw',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Swati',N'SiSwati',N'ss',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Swedish',N'Svenska',N'sv',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Tamil',N'தமிழ்',N'ta',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Telugu',N'తెలుగు',N'te',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Tajik',N'тоҷикӣ toçikī تاجیکی‎',N'tg',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Thai',N'ไทย',N'th',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Tigrinya',N'ትግርኛ',N'ti',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Tibetan',N'བོད་ཡིག',N'bo',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Turkmen',N'Türkmen Түркмен',N'tk',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Tagalog',N'Wikang Tagalog',N'tl',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Tswana',N'Setswana',N'tn',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Tongan (Tonga Islands)',N'Faka Tonga',N'to',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Turkish',N'Türkçe',N'tr',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Tsonga',N'Xitsonga',N'ts',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Tatar',N'татар теле tatar tele',N'tt',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Twi',N'Twi',N'tw',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Tahitian',N'Reo Tahiti',N'ty',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Uighur Uyghur',N'ئۇيغۇرچە‎ Uyghurche',N'ug',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Ukrainian',N'Українська',N'uk',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Urdu',N'اردو',N'ur',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Uzbek',N'Oʻzbek Ўзбек أۇزبېك‎',N'uz',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Venda',N'Tshivenḓa',N've',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Vietnamese',N'Tiếng Việt',N'vi',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Volapük',N'Volapük',N'vo',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Walloon',N'Walon',N'wa',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Welsh',N'Cymraeg',N'cy',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Wolof',N'Wollof',N'wo',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Western Frisian',N'Frysk',N'fy',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Xhosa',N'isiXhosa',N'xh',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Yiddish',N'ייִדיש',N'yi',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Yoruba',N'Yorùbá',N'yo',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Zhuang Chuang',N'Saɯ cueŋƅ Saw cuengh',N'za',0,'2018-11-19')
INSERT INTO LANGUAGES (LanguageNAme, NativeLanguageName,LanguageCode,IsDeleted,CreatedDate) Values(N'Zulu',N'isiZulu',N'zu',0,'2018-11-19')
